name: refiner_sdk
description: Flutter Refiner SDK for iOS, Android and Web
version: 0.0.3
homepage:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: br.com.intelipost.refiner_sdk
        pluginClass: RefinerSdk
      ios:
        pluginClass: RefinerSdk
      web:
        pluginClass: RefinerSdk
        fileName: refiner_sdk.dart